name       : mate-indicator-applet
version    : 1.22.1
release    : 8
source     :
    - https://github.com/mate-desktop/mate-indicator-applet/archive/v1.22.1.tar.gz : ab33939106d3702f03eab6daa67b155ed9221cb99eac18ccada030b1487fba2a
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Panel Indicator Applet
description: |
    A small applet to display information from various applications consistently in the MATE panel.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(indicator3-0.4)
    - itstool
    - mate-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
