name       : mate-indicator-applet
version    : 1.24.0
release    : 9
source     :
    - https://github.com/mate-desktop/mate-indicator-applet/archive/v1.24.0.tar.gz : 4ac497c2ade31b80adee712c2fb740998069ac3d23bba4fbd67f951828e5b029
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Panel Indicator Applet
description: |
    A small applet to display information from various applications consistently in the MATE panel.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(indicator3-0.4)
    - itstool
    - mate-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
