name       : mate-indicator-applet
version    : 1.26.0
release    : 12
source     :
    - https://github.com/mate-desktop/mate-indicator-applet/releases/download/v1.26.0/mate-indicator-applet-1.26.0.tar.xz : e4fbfbede0e58ff7503ead66a3e044ca0f3411a4fd9b552d66e2293a5c828e90
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Panel Indicator Applet
description: |
    A small applet to display information from various applications consistently in the MATE panel.
builddeps  :
    - pkgconfig(ayatana-indicator3-0.4)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libayatana-ido3-0.4)
    - pkgconfig(libmatepanelapplet-4.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
