name       : mate-indicator-applet
version    : 1.16.0
release    : 2
source     :
    - http://pub.mate-desktop.org/releases/1.16/mate-indicator-applet-1.16.0.tar.xz : 5b60ecd36109d2e036b7706fde3c642be3fb157e3189af07017e08b70e55cf21
license    :
    - GPL-3.0
    - LGPL-2.1
component  : desktop.mate
summary    : MATE Panel Indicator Applet
description: |
    MATE Panel Indicator Applet
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(indicator3-0.4)
    - pkgconfig(x11)
    - itstool
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
