name       : mate-indicator-applet
version    : 1.22.0
release    : 7
source     :
    - https://github.com/mate-desktop/mate-indicator-applet/archive/v1.22.0.tar.gz : 2df9841d42d89f0e058a6059db61bfe65e6527f4812b8577710047d26f01f11c
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Panel Indicator Applet
description: |
    A small applet to display information from various applications consistently in the MATE panel.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(indicator3-0.4)
    - itstool
    - mate-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
