name       : mate-indicator-applet
version    : 1.18.1
release    : 4
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-indicator-applet-1.18.1.tar.xz : 3bb6c80ce6356cb0c758cdcc754de7aca2a25739d315ec7ba24885bf5e70e7c0
license    :
    - GPL-3.0
    - LGPL-2.1
component  : desktop.mate
summary    : MATE Panel Indicator Applet
description: |
    MATE Panel Indicator Applet
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(indicator3-0.4)
    - pkgconfig(x11)
    - itstool
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
