name       : mate-indicator-applet
version    : 1.20.1
release    : 6
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-indicator-applet-1.20.1.tar.xz : cd4f5984fe646a7e24e980e658d5bc5875d19494658c9e6b1f03224e06d2b13f
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Panel Indicator Applet
description: |
    MATE Panel Indicator Applet
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(indicator3-0.4)
    - pkgconfig(x11)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
