name       : mate-indicator-applet
version    : 1.27.0
release    : 13
source     :
    - https://github.com/mate-desktop/mate-indicator-applet/releases/download/v1.27.0/mate-indicator-applet-1.27.0.tar.xz : 303efc9b0e0e516b6e324eb740506dd3bdee85411383f96fe54bd059676ad90d
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Panel Indicator Applet
description: |
    A small applet to display information from various applications consistently in the MATE panel.
builddeps  :
    - pkgconfig(ayatana-indicator3-0.4)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libayatana-ido3-0.4)
    - pkgconfig(libmatepanelapplet-4.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
