name       : mate-indicator-applet
version    : 1.20.0
release    : 5
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-indicator-applet-1.20.0.tar.xz : ef5665297ee1d0f2b48153aa81093e69e62b8544b7b8d5d17f17be6e5b9186b9
license    :
    - GPL-3.0
    - LGPL-2.1
component  : desktop.mate
summary    : MATE Panel Indicator Applet
description: |
    MATE Panel Indicator Applet
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(indicator3-0.4)
    - pkgconfig(x11)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
